### ISSUE TITLE
no map after install

### ISSUE THREAD

**Issue by dannytce** [nitaliano/react-native-mapbox-gl#120]
I've tried the example and got this: http://prntscr.com/8vx1yo

There also Warning in console: Warning: Failed propType: typeChecker is not a function Check the render method of `Example`.

All the features work just fine. But i can't see streets, etc.

**Comment by bsudekum** [comment]
Interesting, if you change the style to `light-v8` or `dark-v8`, does the map show up?

**Comment by dannytce** [comment]
Yes, that did the trick. Also `satellite-v8` is working fine. But there is the same problem with `emerald-v8`.

**Comment by syarul** [comment]
what's wrong with streets-v8 most of the time it doesn't seem to work?

**Comment by onchainguy-btc** [comment]
Same issue for me :-(

**Comment by bsudekum** [comment]
This is an upstream issue and will be solved when [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) 3.0.0 is released.

**Comment by bsudekum** [comment]
Check out v2.0.0, this issue should be fixed in it.

**Comment by priithaamer** [comment]
I'm still getting this warning with Mapbox 2.2.0 and react-native 0.16, but only when setting annotations on `<Mapbox annotations={[...]} />` component. When annotations is empty array or entirely missing, the warning is gone.

Now since that yellow warning box was introduced in react-native 0.16 this warning has become very annyoing :) Fortunately, it can be turned off with `console.disableYellowBox = true;` though.
