### ISSUE TITLE
Android installation problem

### ISSUE THREAD

**Issue by sonnylazuardi** [nitaliano/react-native-mapbox-gl#124]
I've followed the steps to install mapbox on my android project. but I got the following error. any idea?

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':reactnativemapboxgl'.
   > Could not resolve all dependencies for configuration ':reactnativemapboxgl:_debugCompile'.
      > Could not find com.android.support:appcompat-v7:23.1.0.
        Searched in the following locations:
            file:/Users/sonnylazuardi/.m2/repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
            file:/Users/sonnylazuardi/.m2/repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
            file:/Users/sonnylazuardi/Downloads/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
            file:/Users/sonnylazuardi/Downloads/android-sdk-macosx/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
            file:/Users/sonnylazuardi/Downloads/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
            file:/Users/sonnylazuardi/Downloads/android-sdk-macosx/extras/google/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
        Required by:
            BusInTime:reactnativemapboxgl:unspecified
      > Could not find com.android.support:appcompat-v7:23.1.0.
        Searched in the following locations:
            file:/Users/sonnylazuardi/.m2/repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
```

**Comment by sonnylazuardi** [comment]
fixed by updating my extras support from android

**Comment by tholhubner** [comment]
I am having this issue now and I do not know how to update my extras support in the current version of Android Studio. I have 26.0.1 installed and all that goes with it, but I am still getting the error above.

**Comment by nitaliano** [comment]
@tholhubner Can you post your gradle files
