### ISSUE TITLE
Android Cannot create a LatLngBounds from 0 items

### ISSUE THREAD

**Issue by atarsha** [nitaliano/react-native-mapbox-gl#586]
I am not a java developer, so this is tough for me to troubleshoot.

I get the following error when calling `this._map.getBounds()`:

`com.mapbox.mapboxsdk.exceptions.InvalidLatLngBoundsException: Cannot create a LatLngBounds from 0 items`

The particular error is a result of the react-native-mapbox-gl code:

https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView.java#L684-L687

Inside of the if statement, we call the LatLngBounds Builder builder() method, which is upstream and defined below:

https://github.com/mapbox/mapbox-gl-native/blob/74bcca380dd7faa7a629d59e3346506e6a8cca34/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java#L428-L433

So it looks like any time _map is null, we are guaranteed to throw an exception. I genuinely don't know why _map is null. I'm calling the getBounds() method from onRegionDidChange.

I created a junk workaround for now, that is pretty hacky to say the least:

```
public LatLngBounds getBounds() {
        if (_map == null) {
            LatLng pointA = new LatLng();
            LatLng pointB = new LatLng();
            ArrayList<LatLng> tmpLatLngs = new ArrayList<LatLng>();
            tmpLatLngs.add(pointA);
            tmpLatLngs.add(pointB);
            return new LatLngBounds.Builder().includes(tmpLatLngs).build();
        }
        return _map.getProjection().getVisibleRegion().latLngBounds;
    }
```

I would very much so welcome some better solutions!

**Comment by butchmarshall** [comment]
I've also been getting this occasionally on startup - thanks!

**Comment by kormang** [comment]
I made a pull request, where I've fixed it. Maybe solution is not the best, but it is certainly better than crashing application. Anyway, I use it in production and it works great for me.
#563 Android improvements

**Comment by vbuch** [comment]
@kormang what do you think of the option of emitting an event _onMapReady() ? This way the RN dev would know when it is safe to request bounds.

**Comment by kormang** [comment]
@vbuch It is good idea. There is few things we should think about before doing that. First, there are no such problems on iOS, and we should not diverge from iOS API. There is also `onFinishLoadingMap` event, having two similar events would make API complicated and would confuse users. Maybe on Android we should emit `onFinishLoadingMap` when both criterion are met When both `onMapReady()` and `onMapChanged(MapView.DID_FINISH_LOADING_MAP)` are called, which ever comes last. I don't know if there is some problem with this approach that I haven't thought about.

**Comment by kormang** [comment]
I'd like to receive some confirmations that above proposed solution is OK, and will gladly make pull request (hopefully just update current PR).

**Comment by henrikra** [comment]
@kormang I think you should make PR and ask feedback there :)

**Comment by kormang** [comment]
Yeah :) I was going to, but you know, people sometimes have tough week. I'll certainly make it in next 7 days. If no one makes it before, of course.

**Comment by kormang** [comment]
I have added commit to the pull request. It is tested and used in production by application I work on.

**Comment by atarsha** [comment]
This issue is still outstanding, and I believe it is the final piece that is preventing me personally from switching off of my forked version. @nitaliano would you mind having a look at @kormang's PR when you get a chance?

If that goes in, that would be a good time for a new release and publishing to NPM because as far as I can tell that SHOULD solve all the common crashes up to RN 0.47.2 (I can't jump to 0.48 yet to test it all due to other dependencies)

**Comment by nitaliano** [comment]
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.

**Comment by gigby** [comment]
@nitaliano 
Probably I this bug still exists in a fresh master (#bfce960333188607) only on Android 8.0.0 and 9.

**Steps to reproduce:**
0) Make an app with router "react-native-router-flux" (I tested only this router) and create several pages (page 1 -> page 2 -> Mapbox page)
1) Init page with map and set up "onRegionDidChange" callback
2) Make two or more fast back actions (from Mapbox page to page 1 for example)

**Error:**

> com.mapbox.mapboxsdk.exceptions.InvalidLatLngBoundsException · Cannot create a LatLngBounds from 1 items

**Stacktrace:**

> LatLngBounds.java:440com.mapbox.mapboxsdk.geometry.LatLngBounds$Builder.build	
> Projection.java:112com.mapbox.mapboxsdk.maps.Projection.getVisibleRegion	
> RCTMGLMapView.java:1268com.mapbox.rctmgl.components.mapview.RCTMGLMapView.makeRegionPayload	
> RCTMGLMapView.java:1478com.mapbox.rctmgl.components.mapview.RCTMGLMapView.handleMapChangedEvent	
> RCTMGLMapView.java:1464com.mapbox.rctmgl.components.mapview.RCTMGLMapView.sendRegionDidChangeEvent	
> RCTMGLMapView.java:91com.mapbox.rctmgl.components.mapview.RCTMGLMapView.access$700	
> RCTMGLMapView.java:1235com.mapbox.rctmgl.components.mapview.RCTMGLMapView$14.run	
> Handler.java:873android.os.Handler.handleCallback	
> Handler.java:99android.os.Handler.dispatchMessage	
> Looper.java:214android.os.Looper.loop	
> ActivityThread.java:7045android.app.ActivityThread.main	
> Method.java:-2java.lang.reflect.Method.invoke	
> RuntimeInit.java:493com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run	
> ZygoteInit.java:964com.android.internal.os.ZygoteInit.main
>

**Comment by kristfal** [comment]
@gigby thanks a lot for steps to reproduce. That makes sense. We already got another issue as #1157, and I do see this issue in production from time to time (we use react-navigation). Let's continue in #1157.
