### ISSUE TITLE
[v6] Style InterpolationMode with non-integer keys crashes example app

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#703]
To reproduce with YoYo example, change the `layerStyles` to include a non-integer key:
```js

const layerStyles = MapboxGL.StyleSheet.create({
  background: {
    backgroundColor: colors.primary.blue,
  },
   water: {
    fillColor: MapboxGL.StyleSheet.camera({
        1: colors.secondary.green,
        8: colors.secondary.orange,
        10: colors.secondary.red,
        18.3: colors.secondary.yellow,
    }, MapboxGL.InterpolationMode.Exponential),
  },
});
```

**Comment by nitaliano** [comment]
@kristfal I'm unable to reproduce this on the `v6` branch. I merged in a PR with some bugfixes yesterday so maybe that fixed the issue you were seeing. Would you be able to test this against the newest `v6`?

I also tested this on
* Android API 26 emulator
* iOS iPhone 7 11.1 simulator

**Comment by kristfal** [comment]
Hey,

This one is strange. I'm not crashing in the simulator, but on-device (iPhone 5S iOS 11.0.3) this is still crashing on the `v6-improvements` branch.

This also seem to be affecting `Categorical` interpolators as well, also in simulators. The iPhone X 11.0 simulator is crashing on the following style:

```js
lineColor: MapboxGL.StyleSheet.source(
        {
          'FOO': 'red',
        },
        'type',
        MapboxGL.InterpolationMode.Categorical,
      ),
```

This doesn't crash:


```js
lineColor: MapboxGL.StyleSheet.source(
        {
          1: 'red',
        },
        'type',
        MapboxGL.InterpolationMode.Categorical,
      ),
```

Also noticed that the Categorical interpolator doesn't differentiate between a key defined as a number or string (`1` or `'1'`). In either case, the former is used in the evaluation on the native side.

**Comment by nitaliano** [comment]
Just wanted to update this ticket, I have this working expect a PR soon.

The only change in the API is the source style function it will look like.
```
MapboxGL.StyleSheet.source([
  [key, value],
  [key, value]
], 'propName', 'interpolationMode');
```

All other style functions(`camera`, `composite`) are being converted to arrays under the hood, since the keys are expected to be camera zoom levels. The new array based API is going to come in handy once we move over to expressions

There's also going to be a new example in the app that uses the source style function with the categorical interpolation mode.
![screenshot 2017-12-06 16 49 46](https://user-images.githubusercontent.com/1761993/33693101-a038bbe8-daa5-11e7-8e86-d2d1f8288bbf.png)

**Comment by nitaliano** [comment]
PR is out https://github.com/mapbox/react-native-mapbox-gl/pull/846

**Comment by kristfal** [comment]
Works like a charm! Super and thanks for fixing it so quickly.
