### ISSUE TITLE
[v6] Android -java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.terminateContext()' on a null object reference

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#749]
I'm seeing this error pop up in our error tracking tools and in the Android Play store pre-launch reports. It's a bit hard to know what the steps are to reproduce, but it looks like something during the app terminating perhaps?

Callstack:
FATAL EXCEPTION: main
Process: com.myapp, PID: 17723
java.lang.RuntimeException: Unable to destroy activity {com.myapp/com.myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.terminateContext()' on a null object reference
  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5061)
  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5084)
  at android.app.ActivityThread.access$1700(ActivityThread.java:221)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1853)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:158)
  at android.app.ActivityThread.main(ActivityThread.java:7224)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.terminateContext()' on a null object reference
  at com.mapbox.mapboxsdk.maps.MapView.onDestroy(MapView.java:264)
  at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$3.onHostDestroy(RCTMGLMapView.java:747)
  at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:231)
  at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:672)
  at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:592)
  at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:606)
  at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:142)
  at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:72)
  at android.app.Activity.performDestroy(Activity.java:7102)
  at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1170)
  at android.support.test.runner.MonitoringInstrumentation.callActivityOnDestroy(MonitoringInstrumentation.java:643)
  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5039)

**Comment by nitaliano** [comment]
We're calling the native `mapView.onDestroy` in the destroy lifecycle the RN gives us access too. I'll debug this to see if this is something that needs to be fixed here or gl-native.

I'm under the assumption that this method should only get called when the app is being destroyed so users shouldn't be seeing any crashes. Have you seen any crashes while the app is open because of this?

**Comment by jliebrand** [comment]
Nope, I think it's only occurring on the pre-launch firebase test lab on our Android Alpha releases...

**Comment by carljoachim** [comment]
My app also crashes on Android with this error message "java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.terminateContext()' on a null object reference" after closing and opening the app around three times..

**Comment by kimhafr** [comment]
This is the full stacktrace we get:

`Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {no.ourapp.staging/no.ourapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.terminateContext()' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4586)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4609)
       at android.app.ActivityThread.-wrap7(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.terminateContext()' on a null object reference
       at com.mapbox.mapboxsdk.maps.MapView.onDestroy(MapView.java:264)
       at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$5.onHostDestroy(RCTMGLMapView.java:812)
       at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:228)
       at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:705)
       at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:614)
       at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:628)
       at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:142)
       at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:72)
       at no.ourapp.MainActivity.onDestroy(MainActivity.java:38)
       at android.app.Activity.performDestroy(Activity.java:7195)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4573)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4609)
       at android.app.ActivityThread.-wrap7(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

We see the crash when this occur (we're using Fabric to log it). Not so easy to reproduce though, we just open and closed the app over and over..

**Comment by nitaliano** [comment]
This was fixed by this PR in GL Native(Android SDK 5.2.1) https://github.com/mapbox/mapbox-gl-native/pull/10589 which is now in master. Going to close this out.

**Comment by butchmarshall** [comment]
I'm still getting error reported pretty frequently even with that pull request?

```
ava.lang.RuntimeException: 
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4639)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:4662)
  at android.app.ActivityThread.-wrap7 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1711)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6688)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: 
  at com.mapbox.mapboxsdk.maps.MapView.onDestroy (MapView.java:410)
  at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$6.onHostDestroy (RCTMGLMapView.java:846)
  at com.facebook.react.bridge.ReactContext.onHostDestroy (ReactContext.java:228)
  at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState (ReactInstanceManager.java:705)
  at com.facebook.react.ReactInstanceManager.onHostDestroy (ReactInstanceManager.java:614)
  at com.facebook.react.ReactInstanceManager.onHostDestroy (ReactInstanceManager.java:628)
  at com.facebook.react.ReactActivityDelegate.onDestroy (ReactActivityDelegate.java:142)
  at com.facebook.react.ReactActivity.onDestroy (ReactActivity.java:72)
  at android.app.Activity.performDestroy (Activity.java:7165)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1161)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4626)
```

**Comment by phares** [comment]
You could be calling the map on the wrong layout.
